### PR TITLE
OK, telemetry again on new branch

### PR DESCRIPTION
**Pull request by ronlawrence3**
Draft only at this point, but behaving ok so far.

### CODE REVIEW

**Comment by BarbourSmith** [comment]
How are we feeling on merging this in? Still not yet?

**Comment by ronlawrence3** [comment]
My confidence level is ~90%. I think without a UI change it won't be generally usable, so I don't see any harm in merging it. I'd love for you to test it if you can... I've tested to some extent and I know that another user has also used it now.

**Comment by ronlawrence3** [comment]
I do have a temporary ui that has menu items for debug on / debug off and debug dump that calls all this, but I have not had time to clean it up enough to pr it.

**Comment by BarbourSmith** [comment]
How do you feel about me merging it in right after tomorrows firmware update? That way we have two full weeks to play with it before it goes out to everyone?

**Comment by ronlawrence3** [comment]
good idea!

**Pull request merged**
